### ISSUE TITLE
where is your getInputStream method

### ISSUE THREAD

**Issue by JamesHe1990** [kennycason/kumo#15]
Hi, I see many of your example using getInputStream method, but the method was not in your code. Do you have a demo.java that can run some example?  Thanks

**Comment by kennycason** [comment]
I didn't provide it since InputStream is a fairly comment Java Interface and there are many method to retrieve an InputStream.

If you want to load an InputStream from a resource that's bundled in a jar (As I did in the examples), You can call:
```java
Thread.currentThread().getContextClassLoader().getResourceAsStream(path)
```
Also note that you can load external files via constructing a FileInputStream

**Comment by kennycason** [comment]
http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html

http://tutorials.jenkov.com/java-io/inputstream.html
