### ISSUE TITLE
Include import statements in README

### ISSUE THREAD

**Issue by tirkarthi** [kennycason/kumo#58]
Thanks for your project. I was trying to build a wrapper around this Java library in Clojure since there were no native word cloud solutions in Clojure. The README examples were missing the import statements that made me search the examples for relevant classes. Improving examples on the README by adding import statements will be great so that the developer can copy paste and run the examples easily to initiate development.

Please point me to links if any that I might be missing.

Thanks

**Comment by tirkarthi** [comment]
I made an initial port at https://github.com/tirkarthi/clj-wordcloud . It seems Travis fails with JDK 7 due to `unsupportedclassversionerror` . I don't know if this is related to the library or due to using it with Clojure.

Travis build failure : https://travis-ci.org/tirkarthi/clj-wordcloud/jobs/356513667

Thanks a lot for the library.

**Comment by kennycason** [comment]
Howdy! Thanks for using Kumo :)

It's because Kumo is written for Java 8. It currently doesn't support Java 7 Many apologies! I just really liked lambdas :)

Thanks for the feedback, I had considered adding imports as well. I'll see how much space it adds to the readme, OR I'll create a class with the examples (which is also a good way to guarantee they compile and are up-to-date and link the readme to the examples so i don't have to add imports to the readme.

**Comment by tirkarthi** [comment]
Cool, no apologies. I was just curious about the error. According to the recent survey only 7% of the Clojure community uses JDK 7 and below with 88% of them on JDK 8. I don't think it will be a major issue. With JDK 10 released I think it's a good move along with the rich set of goodies present in JDK 8 like streams and lambdas.
