### ISSUE TITLE
Add kumo to central maven repo

### ISSUE THREAD

**Issue by theclue** [kennycason/kumo#8]
It would be great if you could add maven into a centralized maven repo. I'm just waiting that to start using this wonderful library at work :)

**Comment by zapodot** [comment]
@kennycason if you need any help with this, let me know :+1:

**Comment by kennycason** [comment]
@zapodot Thanks!

I actually started the process but got rejected because my Jar didn't have sources, (documentation as well?). I wasn't to familiar with the actual process of prepping the project for maven central. If you have a good guide for what to do, or want to submit a PR, I'd be more than happy. I can also easily open the ticket back up after we're ready. 

Work has been kicking by but for the past couple weeks, but I do fully intend on getting this up :)

**Comment by zapodot** [comment]
@kennycason you are almost there... Check my PR for details :-)

**Comment by kennycason** [comment]
Thanks a lot! :)

**Comment by zapodot** [comment]
@kennycason Happy to see this one solved. I guess you can close this ticket now :-)

**Comment by kennycason** [comment]
Yes indeed. Do you by chance know the connection between having my repo in maven central and having it show up in http://mvnrepository.com/ ?
I guess I mistakenly always assumed they were related.

**Comment by zapodot** [comment]
When you deploy a new release it is uploaded to Sonatype's OSS repo.
Periodically the OSS repo is synced with "maven central" (I guess it does
so a few times a day)

The search engine at mvnrepository.com is created by a third party and I
guess is based on some index having to be updated before you will find your
artifact there. Another search engine is http://search.maven.org/ which
should be updated soon after the Sonatype OSS -> central sync has been
completed.

**Comment by kennycason** [comment]
Thanks!
